[XtreemProvider] avoid crash in defered
Obviously the file will not play, due to the broken input, but at least we avoid the crash.

episode["container_extension"] is present but populated with None

13:26:34.7313 Unhandled error in Deferred:
13:26:34.7348 Unhandled Error
Traceback (most recent call last):
File "/usr/lib/python3.13/site-packages/twisted/python/threadpool.py", line 269, in inContext

File "/usr/lib/python3.13/site-packages/twisted/python/threadpool.py", line 285, in <lambda>

File "/usr/lib/python3.13/site-packages/twisted/python/context.py", line 117, in callWithContext

File "/usr/lib/python3.13/site-packages/twisted/python/context.py", line 82, in callWithContext

File "/usr/lib/enigma2/python/Plugins/SystemPlugins/M3UIPTV/plugin.py", line 1173, in getSeriesById
self.episodes = providers[provider].getSeriesById(id)
File "/usr/lib/enigma2/python/Plugins/SystemPlugins/M3UIPTV/XtreemProvider.py", line 218, in getSeriesById
title = title.replace(se_num, "").replace("." + ext, "")
builtins.TypeError: can only concatenate str (not "NoneType") to str